### ISSUE TITLE
Submitting for approval Alert

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#13]
On the pro show page (http://localhost:3000/pros/ID), there is a link at the bottom that let's the users submit information for review by our team.  When the user selects this box, it does save in the database, but there is no save alert.  I tried to add in the 'create' save function in the controller but got that it was missing the ID Params

ActionController::ParameterMissing in ProsController#show
param is missing or the value is empty: pro

**Comment by nolanzandi** [comment]
![image](https://cloud.githubusercontent.com/assets/2481116/12506114/6a9bab1e-c0a1-11e5-9f66-10f12036d0f3.png)

Is this what you were looking for? I submitted a pull request and my Git commit is here: https://github.com/g00dL00Ks/ruby/commit/311ce7849b651b7f3830cc4f03657a9b2fcfa727

Total time: 1 hour

**Comment by g00dL00Ks** [comment]
The good news is that the approval is working, which is great. 

My only other question is if we can have a different message depending on where the user saves.  If they check the box on the bottom of the page from your screen shot and hit submit,we want it to say "Submitted for approval!".  

However if they are editing their info on #1 (Share your expertise) they will get the same message b/c it's the same form.  Is there anyway to separate the messages?  

For now, I've just updated the message to make it a save message. 

thank you!

**Comment by nolanzandi** [comment]
I should definitely be able to separate the messages. 

Sent from Yahoo Mail on Android 

  On Fri, Jan 22, 2016 at 10:39 AM, g00dL00Ksnotifications@github.com wrote:  
The good news is that the approval is working, which is great. 

My only other question is if we can have a different message depending on where the user saves. If they check the box on the bottom of the page from your screen shot and hit submit,we want it to say "Submitted for approval!". 

However if they are editing their info on #1 (Share your expertise) they will get the same message b/c it's the same form. Is there anyway to separate the messages? 

For now, I've just updated the message to make it a save message. 

thank you!

**Comment by nolanzandi** [comment]
@g00dL00Ks What field in Pros gets edited if the Submit for Approval box is checked and the button is pushed?

Trying to figure out a function to tell the difference between a normal update and a submission for approval.

**Comment by g00dL00Ks** [comment]
The field is review.  A boolean field
tells us to review their profile for publishing

**Comment by nolanzandi** [comment]
@g00dL00Ks I believe I have it working. I'm able to set two different Pro profile update messages for the main pro page depending on if the submit for review button is checked or not:

![image](https://cloud.githubusercontent.com/assets/2481116/12527613/6bc3b792-c133-11e5-9796-3d9246a71d78.png)

![image](https://cloud.githubusercontent.com/assets/2481116/12527615/6fe56b9a-c133-11e5-907b-ef4cfaf786c6.png)

Let me know if its working for you and I submitted a pull request for the merge if it works. 

Total time on issue: 2 hours

**Comment by g00dL00Ks** [comment]
works great!  I am pushing live now
