### ISSUE TITLE
portfolio images for pros

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#2]
I want pros to be able to upload a portfolio of images.  I've got the photos database working but having trouble displaying them on pro show page (pro_path)

**Comment by nolanzandi** [comment]
@g00dL00Ks How do you access the pro show page within the site? What's the url on https://goodlooks.herokuapp.com/ so I can find and see what's currently displaying.

**Comment by g00dL00Ks** [comment]
Here it is:  http://insider.marsmerize.com/pros/1
Obviously dependent on the pro user ID

**Comment by nolanzandi** [comment]
@g00dL00Ks Thanks. Could I get your application.yml file for this app as well so I can see the photos locally?

**Comment by g00dL00Ks** [comment]
Yes! Sorry I forgot to send!

I just stopped out but will send in about an hour

On Sat, Jan 16, 2016 at 3:36 PM -0800, "Nolan Zandi" <notifications@github.com<mailto:notifications@github.com>> wrote:

@g00dL00Kshttps://github.com/g00dL00Ks Thanks. Could I get your application.yml file for this app as well so I can see the photos locally?

##

**Comment by nolanzandi** [comment]
No worries. About to grab lunch anyway. Just FYI I'll probably out of range after about 7pm but will be back tomororw.

**Comment by g00dL00Ks** [comment]
Ok just sent it to you via email. Thank you for your help with this.  I really appreciate it

**Comment by nolanzandi** [comment]
![image](https://cloud.githubusercontent.com/assets/2481116/12375389/f62814be-bc74-11e5-814d-05fb58fb5bbe.png)

Ok so I only saw the ability to upload 1 image in the pro creation page, so this isn't optimized to show a full gallery (although that shouldn't be hard). 

One thing to note: I wasn't able to access the photos model via the pro. I called the photo by calling the image method on the pro. The image method does find the right AWS S3 url and seems to be connected properly, but I'm not sure what you had planned with the Photo model. If the professional photos were supposed to called through the Photo method, then we might have to do some work to figure out what happened but it just depends on how you intended this to work. 

This is my commit if you want to take a look at what I did (for both issues). Let me know if/when you want a push to master as well. 
https://github.com/g00dL00Ks/ruby/commit/cd36cc68c0feb9e1b9e66b647aa5af7fd27a276e

Total time so far on task: 1.5 hours

**Comment by g00dL00Ks** [comment]
Yes I hadn't linked the photos upload page yet to the pro signup
But you can see a link if you go to the account page of where to upload additional photos. Also you can find the page if you rake routes

On Sat, Jan 16, 2016 at 5:26 PM -0800, "Nolan Zandi" <notifications@github.com<mailto:notifications@github.com>> wrote:

[image]https://cloud.githubusercontent.com/assets/2481116/12375389/f62814be-bc74-11e5-814d-05fb58fb5bbe.png

Ok so I only saw the ability to upload 1 image in the pro creation page, so this isn't optimized to show a full gallery (although that shouldn't be hard).

One thing to note: I wasn't able to access the photos model via the pro. I called the photo by calling the image method on the pro. The image method does find the right AWS S3 url and seems to be connected properly, but I'm not sure what you had planned with the Photo model. If the professional photos were supposed to called through the Photo method, then we might have to do some work to figure out what happened but it just depends on how you intended this to work.

This is my commit if you want to take a look at what I did (for both issues). Let me know if/when you want a push to master as well.
cd36cc6https://github.com/g00dL00Ks/ruby/commit/cd36cc68c0feb9e1b9e66b647aa5af7fd27a276e

##

**Comment by nolanzandi** [comment]
OK so is there more than one photo already in the database for pro 1? If not could you add a few more and then I can work on displaying them? When I try and upload photos here Im getting an error. 

Sent from Yahoo Mail on Android 

  On Sat, Jan 16, 2016 at 5:35 PM, g00dL00Ksnotifications@github.com wrote:   Yes I hadn't linked the photos upload page yet to the pro signup
But you can see a link if you go to the account page of where to upload additional photos. Also you can find the page if you rake routes

On Sat, Jan 16, 2016 at 5:26 PM -0800, "Nolan Zandi" <notifications@github.com<mailto:notifications@github.com>> wrote:

[image]https://cloud.githubusercontent.com/assets/2481116/12375389/f62814be-bc74-11e5-814d-05fb58fb5bbe.png

Ok so I only saw the ability to upload 1 image in the pro creation page, so this isn't optimized to show a full gallery (although that shouldn't be hard).

One thing to note: I wasn't able to access the photos model via the pro. I called the photo by calling the image method on the pro. The image method does find the right AWS S3 url and seems to be connected properly, but I'm not sure what you had planned with the Photo model. If the professional photos were supposed to called through the Photo method, then we might have to do some work to figure out what happened but it just depends on how you intended this to work.

This is my commit if you want to take a look at what I did (for both issues). Let me know if/when you want a push to master as well.
cd36cc6https://github.com/g00dL00Ks/ruby/commit/cd36cc68c0feb9e1b9e66b647aa5af7fd27a276e

##

**Comment by g00dL00Ks** [comment]
Is there a way I can see the data tables in Amazon? I'm having trouble finding them and I find it a useful way to check my info submitted
thanks

**Comment by g00dL00Ks** [comment]
Hi Nolan - Just to clarify on this, we ask the pro to set their profile image when they are signing up.  

They can then also add "photos" which we intend to be portfolio photos of their work.  

I have issues with images loading locally for me, so the best way for you to test it is to create a pro and then try to add images.  You can access the path to add images here:
insider.marsmerize.com/pros/[PRO_ID]

I think when the images are saving, they aren't being associated with the user.  Although, i'm not 100% sure b/c i'm not sure where to find the data tables in amazon (I was originally checking locally).

**Comment by nolanzandi** [comment]
Hey just wanted to give a status update. I've put about 4 hours into this today. It's a pretty tough one because there seems to be a lot of different affecting forces to the issue. It was true that it wasn't saving the photos and it wasn't previously attaching them to the Pro. I've gotten it to try to save the photos and attach it to the pro, but I'm still having trouble getting all the attributes to line up. Paperclip can be challenging to configure, although that isn't a knock against it as a good solution. See my progress below, photos saving, but not all the data:

![image](https://cloud.githubusercontent.com/assets/2481116/12388975/d30355e0-bd8a-11e5-913f-f9b83426cfbb.png)

I'm going to be really swamped the next couple of days, but I'll do all I can to get in a couple hours each day on this for you and hopefully some more time will clear up in the middle of the week and beyond. 

I'd of course be happy to push my work so far if you want to play with it (my branch also fixed the issue in production with the Pros pages)

Total time so far: 4 hours

**Comment by nolanzandi** [comment]
Got it! 

![image](https://cloud.githubusercontent.com/assets/2481116/12392702/bf5c9950-bda5-11e5-8077-824bb8f5a64c.png)

I merged my branch with master so i could test if it worked in production and it did (I would have just rolled back if it didnt). There's still some cleanup, but after a grueling push, at least were getting somewhere. 

Total time so far: 5 hours

**Comment by g00dL00Ks** [comment]
Yeah!  thank you so much!  I'm glad I gave you a task worthy of your skills :)

**Comment by g00dL00Ks** [comment]
Works great!
