### ISSUE TITLE
User confirmation emails

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#4]
When a user signs up, I'd like them to get a confirmation email.  or when they forgot a password. I think this is something devise can automatically send, but our app hasn't activated it. Can you look at turning that on?

**Comment by g00dL00Ks** [comment]
@nolanzandi do you have a recommendation of a good mail gem? I'm thinking of using mailer but wanted to know if there is another one you recommend?

**Comment by nolanzandi** [comment]
@g00dL00Ks Is this for the confirmation emails (which should be via devise)? Or is this for other emails you want to send?

**Comment by g00dL00Ks** [comment]
It's for devise... I need to activate the emails and I think I need to set-up something like mailer to send them.

**Comment by nolanzandi** [comment]
@g00dL00Ks Oh yeah, so Devise is configured to use ActionMailer, so you'd probably want to use that. This might point in the right direction: http://stackoverflow.com/questions/4445258/rails-3-devise-confirmation-email-server-settings

I'd be happy to help set it up, but I'm pretty slammed until Wed at the earliest. I'll definitely try to put in a couple hours tomorrow.

**Comment by g00dL00Ks** [comment]
Hi there. 
When you've got time, I could use your help with this one

I've done the following:
Based on the stack-overflow article, I followed these directions (as relevant)
http://edgeguides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration
And I can successfully generate a preview here:  http://localhost:3000/rails/mailers/user_mailer/welcome_email

I activated SendGrid on Heroku according to this:
https://devcenter.heroku.com/articles/sendgrid

On my local host i'm able to register without an error.   on the live server, i get an error.  

as a result, in the registrations_controller.rb, I've commented out:
    # UserMailer.welcome_email(@user).deliver

So now the site is working again but not sending emails.  

thanks for looking at it when you have a moment

**Comment by nolanzandi** [comment]
![image](https://cloud.githubusercontent.com/assets/2481116/12475092/31556114-bfd5-11e5-9c39-fac257ef2121.png)

I believe that user confirmations are are working. It takes about 30 seconds for the email to arrive from what I see. Do some testing and let me know what you think.

Total time so far: 2 hours

**Comment by g00dL00Ks** [comment]
Emails are working!  We're just working now on getting it working on experts.goodlooks.me

**Comment by g00dL00Ks** [comment]
Working! and we got it set-up on experts.goodlooks.me
