### ISSUE TITLE
Links not working in IE and Firefox

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/ruby#7]
@nolanzandi 
Hi Nolan - I know you are slammed, but wondering if you have any quick tips.  The button links on http://insider.marsmerize.com/ aren't working on IE and Firefox.  I'm doing some googling around but haven't found anything obvious. Have you come across this before?

thanks

**Comment by g00dL00Ks** [comment]
Sorry - think i found the answer.  Will close out if i get it.  (murphy's law that i find it after i ping you!)

**Comment by nolanzandi** [comment]
Haha no worries. I'm traveling most of the day but I can probably take a look this evening if there are still outstanding questions on it. 

Sent from Yahoo Mail on Android 

  On Tue, Jan 19, 2016 at 11:25 AM, g00dL00Ksnotifications@github.com wrote:  
Sorry - think i found the answer. Will close out if i get it. (murphy's law that i find it after i ping you!)

**Comment by g00dL00Ks** [comment]
Ok sounds good - turns out i was calling my buttons wrong.  Hope your travels go well!
